### PR TITLE
Add PyBacting example for parsing IUPAC names

### PR DESCRIPTION
**Pull request by cthoyt**
I think this is what you were asking for in https://twitter.com/egonwillighagen/status/1477552192760520706, right?

### CODE REVIEW

**Comment by egonw** [comment]
Yes, something like this. Now, the `code/ParseIUPACName.code.md` file is autogenerated from https://github.com/bioclipse/bioclipse.scripting/blob/master/code/ParseIUPACName.groovyin so I need to get my head around on how to integrate this...

**Comment by egonw** [comment]
Alternatively, what about this:

```
~groovy:@Grab(group='io.github.egonw.bacting', module='managers-opsin', version='0.0.29')
~groovy:workspaceRoot = "../ws"
~groovy:opsin = new net.bioclipse.managers.OpsinManager(workspaceRoot);
~python:from pybacting import opsin
~
mol = opsin.parseIUPACName(
  "Ethyl [(1R,3aR,4aR,6R,8aR,9S,9aS)-9-" +
  "{(E)-2-[5-(3-fluorophenyl)-2-pyridinyl]vinyl}-" +
  "1-methyl-3-oxododecahydronaphtho[2,3-c]furan-" +
  "6-yl]carbamate"
)
~groovy:println mol
~python:print(mol)
```

?

**Comment by cthoyt** [comment]
I think this example was pretty simple but there will probably be places where the syntax of the language diverges so I'd suggest making separate files for python. I'm not sure what the `~` and `#` markup were for, though

**Comment by egonw** [comment]
Okay, all set up now, including "Open in Google Colab" :)

**Pull request closed without merging**
